[package]
name = "minicon"
version = "0.1.0"
authors = ["smiyaguchi <smiyaguchi96@gmail.com>"]

[dependencies]
clap = {version = "2.32", features = ["yaml"]}
failure = "0.1.3"
lazy_static = "1.2.0"
nix = "0.12.0"
serde = "1.0.80"
serde_derive = "1.0.80"
serde_json = "1.0.33"
