[package]
name = "minicon"
version = "0.1.0"
authors = ["smiyaguchi <smiyaguchi96@gmail.com>"]
description = "minicon is minimal container runtime."

[dependencies]
clap = {version = "2.30", features = ["yaml"]}
error-chain = "0.11.0"
nix = "0.10.0"
